ALL = 'all'
RENDER = 'render'
ANALYZE = 'analyze'
FOLDER = 'folder'
FILE = 'file'
NORMALISE = 'normalise'
EXPORT = 'export'
GRAPH = 'graph'
FEATURE = 'feature'

BASICDATA = 'basicdata'
NORMALISED = 'normalised'